version: '3'

services:

  wmvpdev:
    container_name: wmvpdev
    build: '.'
    ports:
      - "8080:80"
    volumes:
      - ./resources:/var/www/resources:rw
      - ./app:/var/www/app:rw
    depends_on:
      - wmvpdb
      - wmvpseeds

  wmvpseeds:
    container_name: wmvpseeds
    build: './db_stuff'
    ports:
      - "8081:80"
    volumes:
      - ./db_stuff/migrations:/app/migrations:rw
      - ./db_stuff/models:/app/models:rw
      - ./db_stuff/seeders:/app/seeders:rw
    depends_on:
      - wmvpdb

  admin:
    container_name: admin
    image: adminer
    restart: always
    depends_on:
      - wmvpdb
    ports:
      - "8082:8080"

  wmvpdb:
    container_name: wmvpdb
    image: mdillon/postgis
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  pgdata: