apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.kompose.service: wmvpdev
    name: wmvpdev
    namespace: wmvp
  spec:
    type: LoadBalancer
    ports:
    - name: "3000"
      port: 3000
      targetPort: 80
    selector:
      io.kompose.service: wmvpdev
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      io.kompose.service: wmvpdev
      keel.sh/policy: force
      keel.sh/match-tag: "true"
    name: wmvpdev
    namespace: wmvp
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app: wmvpdev
    strategy: {}
    template:
      metadata:
        name: wmvpdev
        creationTimestamp: null
        labels:
          io.kompose.service: wmvpdev
          app: wmvpdev
      spec:
        containers:
        - image: ccccontainers.azurecr.io/wmvp:dev
          imagePullPolicy: Always
          name: wmvpdev
          ports:
          - containerPort: 3000
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}