version: 2.0
jobs:
  BuildPushMaster:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            echo APP_ENV=${APP_ENV} >> .env
            echo APP_DEBUG=${APP_DEBUG} >> .env
            echo APP_KEY=${APP_KEY} >> .env
            echo APP_URL=${APP_URL} >> .env
            echo DEV_SQLSRV_HOST=${DEV_SQLSRV_HOST} >> .env
            echo DEV_SQLSRV_DATABASE=${DEV_SQLSRV_DATABASE} >> .env
            echo DEV_SQLSRV_USERNAME=${DEV_SQLSRV_USERNAME} >> .env
            echo DEV_SQLSRV_PASSWORD=${DEV_SQLSRV_PASSWORD} >> .env
            echo SQLSRV_HOST=${SQLSRV_HOST} >> .env
            echo SQLSRV_DATABASE=${SQLSRV_DATABASE} >> .env
            echo SQLSRV_USERNAME=${SQLSRV_USERNAME} >> .env
            echo SQLSRV_PASSWORD=${SQLSRV_PASSWORD} >> .env
            echo CACHE_DRIVER=${CACHE_DRIVER} >> .env
            echo SESSION_DRIVER=${SESSION_DRIVER} >> .env
            echo QUEUE_DRIVER=${QUEUE_DRIVER} >> .env
            echo MAIL_DRIVER=${MAIL_DRIVER} >> .env
            echo MAIL_HOST=${MAIL_HOST} >> .env
            echo MAIL_PORT=${MAIL_PORT} >> .env
            echo LARAVEL_DEBUGBAR=${LARAVEL_DEBUGBAR} >> .env
            echo CCC_ICONS_SVG=${CCC_ICONS_SVG} >> .env
            echo -e "text\n" >> .env
            docker build . -t ${registryName}.azurecr.io/wmvp:latest
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/wmvp:latest
  BuildPushDev:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and Push to ACR
          command: |
            echo APP_ENV=${APP_ENV} >> .env
            echo APP_DEBUG=${APP_DEBUG} >> .env
            echo APP_KEY=${APP_KEY} >> .env
            echo APP_URL=${APP_URL} >> .env
            echo DEV_SQLSRV_HOST=${DEV_SQLSRV_HOST} >> .env
            echo DEV_SQLSRV_DATABASE=${DEV_SQLSRV_DATABASE} >> .env
            echo DEV_SQLSRV_USERNAME=${DEV_SQLSRV_USERNAME} >> .env
            echo DEV_SQLSRV_PASSWORD=${DEV_SQLSRV_PASSWORD} >> .env
            echo SQLSRV_HOST=${SQLSRV_HOST} >> .env
            echo SQLSRV_DATABASE=${SQLSRV_DATABASE} >> .env
            echo SQLSRV_USERNAME=${SQLSRV_USERNAME} >> .env
            echo SQLSRV_PASSWORD=${SQLSRV_PASSWORD} >> .env
            echo CACHE_DRIVER=${CACHE_DRIVER} >> .env
            echo SESSION_DRIVER=${SESSION_DRIVER} >> .env
            echo QUEUE_DRIVER=${QUEUE_DRIVER} >> .env
            echo MAIL_DRIVER=${MAIL_DRIVER} >> .env
            echo MAIL_HOST=${MAIL_HOST} >> .env
            echo MAIL_PORT=${MAIL_PORT} >> .env
            echo LARAVEL_DEBUGBAR=${LARAVEL_DEBUGBAR} >> .env
            echo CCC_ICONS_SVG=${CCC_ICONS_SVG} >> .env
            echo -e "text\n" >> .env
            docker build . -t ${registryName}.azurecr.io/wmvp:dev
            docker login ${registryName}.azurecr.io -u ${registryName} -p ${registryPassword}
            docker push ${registryName}.azurecr.io/wmvp:dev
workflows:
  version: 2
  WMVP_Workflow:
    jobs:
      - BuildPushMaster:
          filters:
            branches:
              only: master
      - BuildPushDev:
          filters:
            branches:
              only: dev